-- Step 2: Insert first competition data (run after 004)
INSERT INTO competitions (
  id,
  title,
  slug,
  description,
  long_description,
  edition,
  status,
  start_date,
  end_date,
  registration_deadline,
  location,
  cover_image,
  poster_image,
  video_url,
  philosophy,
  purpose,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  '제1회 우주 최고 실패 대회',
  'first-competition',
  '실패, 결과가 아닌 질문으로 바꾸다',
  '제1회 우주 최고 실패 대회는 "단순히 실패를 극복하고 결국 희망과 웃음으로 마무리하는 자리"가 아닙니다. 포항 지역 최초의 실패 독려 프로젝트로서, 실패를 개인의 낙인으로 치부하지 않고 사회가 함께 격려하고 축하하는 축제의 장을 마련하고자 합니다. 참가자 모두가 자신이 극복하지 못한 실패를 진솔하게 나누는 것이 이 대회의 가장 중요한 목표입니다.',
  1,
  'ongoing',
  '2025-01-15T10:00:00+09:00',
  '2025-01-15T18:00:00+09:00',
  '2025-01-10T23:59:59+09:00',
  '포항시',
  '/images/poster.jpg',
  '/images/poster.jpg',
  'https://player.vimeo.com/video/1123631620?title=0&byline=0&portrait=0&badge=0&autopause=0&player_id=0&app_id=58479',
  '실패는 개인의 몫처럼 보이지만, 사실은 사회가 함께 책임져야 할 감정',
  '만약 실패를 공유할 수 있는 언어와 공간이 없다면 실패는 그저 실패로 끝날 수밖에 없습니다. 하지만 실패를 나누고 교류하는 과정에서 실패를 조금씩 익숙하게 받아들이고, 이로써 실패는 실패 이후로 나아가게 됩니다. 단순히 희망적이고 성공담으로 포장하지 않은 실패 그 자체를, 있는 그대로 회고하는 순간을 만들어 많은 분들의 이야기를 들려드리고 싶습니다.',
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  long_description = EXCLUDED.long_description,
  edition = EXCLUDED.edition,
  status = EXCLUDED.status,
  philosophy = EXCLUDED.philosophy,
  purpose = EXCLUDED.purpose,
  updated_at = NOW();
